# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 629fca65de5188db91bcf4527efd6b1279e8042684adb6656b4e2a0efec9876d93fc900a6cdbfa75feaa7001ba44cd6d0f13fb28d43bbb4a49506fabc743602e

test:
  secret_key_base: a192a50c53502ce04f906fe88473a9758e35b9bf3747acd07bb0e3ddfbfffe5506d971313967c107d8bd09801ae7f03140a3b435538f5a10b47ae8ea9123f58e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
